name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      teste: ${{steps.step_one.outputs.FOO}}
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "FOO=$(whoami)" >> $GITHUB_OUTPUT
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.step_one.outputs.FOO }}"

  outro:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get the value
        id: step_two
        run: |
          echo "${{ needs.build.outputs.teste }}"
          
  finally:
    name: finally
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: development
    steps:
      - name: restart last container
        uses: fifsky/ssh-action@master
        
        if: ${{ failure() }}
        with:
          command: |

            cd dev/${{ github.event.repository.name }}
            docker rmi $(cat new_image_id.txt)
                  
          host: ${{ vars.HOST }}
          user: ${{ vars.SSH_USER }}
          key: ${{ secrets.SECRET_KEY }}


      - name: clean images
        uses: fifsky/ssh-action@master
        if: ${{ success() }}
        with:
          command: |
            cd dev/${{ github.event.repository.name }}
            docker rmi $(cat old_image_id.txt)

          host: ${{ vars.HOST }}
          user: ${{ vars.SSH_USER }}
          key: ${{ secrets.SECRET_KEY }}
