name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      teste: ${{steps.step_one.outputs.FOO}}
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "FOO=$(whoami)" >> $GITHUB_OUTPUT
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.step_one.outputs.FOO }}"

  outro:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get the value
        id: step_two
        run: |
          echo "${{ needs.build.outputs.teste }}"
              
  deploy-hml:
    name: deploy-hml
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: starting server
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo "teste"
    - name: restart last container
      uses: fifsky/ssh-action@master
      if: ${{ failure() }}
      with:
          command: |
            echo "teste"

    - name: clean images
      uses: fifsky/ssh-action@master

      if: ${{ success() }}
      with:
        command: |
          echo "teste

  deploy-prd:
    name: deploy-prd
    needs: deploy-hml
    runs-on: ubuntu-latest
    steps:    
    - name: building image
      uses: fifsky/ssh-action@master
      with:
        command: |
          echo "teste"
    - name: starting server
      uses: fifsky/ssh-action@master
      with:
        command: | 
          echo "teste"
    - name: restart last container
      uses: fifsky/ssh-action@master
      if: ${{ failure() }}
      with:
        command: |
           echo "teste"

    - name: clean images
      uses: fifsky/ssh-action@master
      if: ${{ success() }}
      with:
        command: |
           echo "teste"
        
