name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      teste: ${{steps.step_one.outputs.FOO}}
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "FOO=$(whoami)" >> $GITHUB_OUTPUT
      - name: Use the value
        id: step_two
        run: |
          echo "${{ steps.step_one.outputs.FOO }}"

  outro:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get the value
        id: step_two
        run: |
          echo "${{ needs.build.outputs.teste }}"
          
  finally:
    runs-on: ubuntu-latest
    needs: [outro, build]
    steps:
      - name: notify of failure
        if: ${{ failure() }}
        with:
          text: ":heavy_check_mark: Build success - Deploy -  Server - TEST - Azure Web pps CI/CD. :heavy_check_mark:"             
      - name: notify of success
        if: ${{ success() }}
        with:
          text: ":heavy_check_mark: Build success - Deploy -  Server - TEST - Azure Web pps CI/CD. :heavy_check_mark:"     
